openapi: 3.0.3
info:
  title: MSID Management API
  description: API for reading, inserting, and updating MSID records. All endpoints require authorization parameters in the request body.
  version: 1.0.0

paths:
  /read:
    post:
      summary: /Read Endpoint
      description: Retrieve existing Msids in the system given the filter criteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [partyID, username, partyAPIKey]
              properties:
                partyID:
                  type: string
                username:
                  type: string
                partyAPIKey:
                  type: string
                pendingFlag:
                  type: string
                  enum: [D, P, PA, S, R]
                SVABMUnit:
                  type: string
                  description: BM Unit Id (V__AFLEX003)
                effectiveFromDate:
                  type: string
                  pattern: '^\d{8}$'
                effectiveToDate:
                  type: string
                  pattern: '^\d{8}$'
                lastModifiedDate:
                  type: string
                  pattern: '^\d{8}$'
                MsidAmsidRequestID:
                  type: string
      responses:
        '200':
          description: List of MSIDs matching filters
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    SVA_BM_Unit: "V__PFLEX001"
                    Pending_Flag: "R"
                    MSID_Pair_ID: "a0sAe000001xJvhIAE"
                    Last_Modified_Date: "2025-07-02 14:39:47"
                    Import_Reject_Reasons: "MSID does not exist"
                    Import_Metering_System: "4883772918844"
                    GSP_Group: "_P"
                    Export_Reject_Reasons: ""
                    Export_Metering_System: ""
                    Effective_To_Settlement_Date: "02/07/2025"
                    Effective_From_Settlement_Date: "29/04/2025"
        '400':
          $ref: '#/components/responses/InvalidParameters'
        '403':
          $ref: '#/components/responses/AuthorizationError'

  /insert:
    post:
      summary: /Insert Endpoint
      description: Submit Msid for business validations and insertion on the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [partyID, username, partyAPIKey]
              properties:
                partyID:
                  type: string
                username:
                  type: string
                partyAPIKey:
                  type: string
                MsidAmsidsToInsert:
                  type: array
                  description: List of MSIDs to insert. Each item has a row number and a CSV string in `data`
                  items:
                    type: object
                    properties:
                      row:
                        type: string
                        description: "Row index"
                      data:
                        type: string
                        description: |
                          Comma Separated Values string with MSID data fields in order (*)mandatory:
                          1. BMUnitID (max 11 chars) *
                          2. GSPGroup (2 chars) *
                          3. Effective From Settlement Date {MSIDP} (DD/MM/YYYY) *
                          4. Effective To Settlement Date {MSIDP} (DD/MM/YYYY) *
                          5. Import MSID (13 chars) *
                          6. Import MSID Customer Consent Flag (Y/N) *
                          7. Effective From Settlement Date {ICCF} (DD/MM/YYYY) *
                          8. Effective To Settlement Date {ICCF} (DD/MM/YYYY) *
                          9. Export MSID (13 chars)
                          10. Export MSID Customer Consent Flag (Y/N)
                          11. Effective From Settlement Date {ECCF} (DD/MM/YYYY)
                          12. Effective To Settlement Date {ECCF} (DD/MM/YYYY)
                        example: "V__AFLEX001,_L,01/06/2025,10/06/2025,2242026341161,Y,03/06/2025,10/12/2025,3663328556786,Y,03/06/2025,10/06/2025"
      responses:
        '200':
          description: MSIDs processed successfully and accepted for insertion on the system
          content:
            application/json:
              schema:
                type: object
                example:
                  status: "Accepted"
                  requestId: "FLEXTRCY_MSID-PAIR-ALLOC-CREATE_20250331151154"
        '202':
          description: Partial success with errors during insert operation
          content:
            application/json:
              schema:
                type: object
                example:
                  status: "Accepted_with_errors"
                  MSIDAMSIDRequestId: "FLEXTRCY_MSID-PAIR-ALLOC-CREATE_20250331151154"
                  errors:
                    - row: "1"
                      data: "The MSID Pair Effective From Date must be at least 1 Working Day in the future."
        '400':
          description: Bad Request - Invalid parameters or limits reached
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/InvalidParameters'
                  - $ref: '#/components/schemas/LimitErrorReached'
                  - $ref: '#/components/schemas/PayloadLimit'                  
        '403':
          $ref: '#/components/responses/AuthorizationError'

  /update:
    post:
      summary: /Update Endpoint 
      description: Update {Effective From Date} Or {Customer Consent Flag} independently
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required: [partyID, username, partyAPIKey, MsidAmsidsToUpdate]
                  properties:
                    partyID:
                      type: string
                    username:
                      type: string
                    partyAPIKey:
                      type: string
                    MsidAmsidsToUpdate:
                      type: array
                      items:
                        type: object
                        properties:
                          row:
                            type: string
                          data:
                            type: string
                            description: "MSIDId,EffectiveToSettlementDate"
                - type: object
                  required: [partyID, username, partyAPIKey, ConsentFlagsToUpdate]
                  properties:
                    partyID:
                      type: string
                    username:
                      type: string
                    partyAPIKey:
                      type: string
                    ConsentFlagsToUpdate:
                      type: array
                      items:
                        type: object
                        properties:
                          row:
                            type: string
                          data:
                            type: string
                            description: "MSIDId,MPAN,ConsentFlag,ConsentEffectiveFromDate,FlowDirection"
      responses:
        '200':
          description: MSIDs processed successfully and accepted for insertion on the system
          content:
            application/json:
              schema:
                type: object
                example:
                  status: "Accepted"
                  MSIDAMSIDRequestId: "FLEXTRCY_MSID-PAIR-ALLOC-UPDATE_20250331151154"
        '202':
          description: Partial success with errors during update operation
          content:
            application/json:
              schema:
                type: object
                example:
                  status: "Accepted_with_errors"
                  MSIDAMSIDRequestId: "FLEXTRCY_MSID-PAIR-ALLOC-UPDATE_20250331151154"
                  errors:
                    - row: "2"
                      data: "MSID Pair must be in Pending Status 'S'"
        '400':
          description: Bad Request - Invalid parameters or limits reached
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/InvalidParameters'
                  - $ref: '#/components/schemas/LimitErrorReached'
                  - $ref: '#/components/schemas/PayloadLimit'                  
        '403':
          $ref: '#/components/responses/AuthorizationError'

components:
  responses:
    InvalidParameters:
      description: Payload does not conform to API specification
      content:
        application/json:
          schema:
            type: object
            example:
              message: "Invalid parameters, please check the API documentation"

    AuthorizationError:
      description: Authorization failure (invalid API key or unauthorized username)
      content:
        application/json:
          schema:
            type: object
            oneOf:
              - example:
                  message: "The provided username and party combination is not authorized."
              - example:
                  message: "The provided username and partyID combination is not authorized."

    InvalidEndpoint:
      description: Operation type is invalid
      content:
        application/json:
          schema:
            type: object
            example:
              message: "Invalid endpoint. Accepted endpoints are: Read, Insert, Update"

    LimitErrorReached:
      description: Errors in the payload exceeds the limit defined inside Salesforce (500)
      content:
        application/json:
          schema:
            type: object
            example:
              message: "Wrong Payload: Maximum number of row errors reached (stored_parameter_number 500)"

    PayloadLimit:
      description: Errors in the payload, volume of records exceeds the Salesforce stored parameter limit (2000)
      content:
        application/json:
          schema:
            type: object
            example:
              message: "Payload too large, exceeded maximum number of records allowed in Update API"   
