openapi: 3.0.3
info:
  title: MSID Management API
  description: API for reading, inserting, and updating MSID records. All endpoints require authorization parameters in the request body.
  version: 1.0.0

paths:
  /read:
    post:
      summary: Retrieve MSID records
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [partyID, username, partyAPIKey]
              properties:
                partyID:
                  type: string
                username:
                  type: string
                partyAPIKey:
                  type: string
                pendingFlag:
                  type: string
                  enum: [D, P, PA, S, R]
                SVABMUnit:
                  type: string
                  description: BM Unit Id (V__AFLEX003)
                effectiveFromDate:
                  type: string
                  pattern: '^\d{8}$'
                effectiveToDate:
                  type: string
                  pattern: '^\d{8}$'
                lastModifiedDate:
                  type: string
                  pattern: '^\d{8}$'
                MsidAmsidRequestID:
                  type: string
      responses:
        '200':
          description: List of MSIDs matching filters
          content:
            application/json:
              schema:
                type: object
                example:
                  status: "success"
                  data: []
        '400':
          $ref: '#/components/responses/InvalidParameters'
        '403':
          $ref: '#/components/responses/AuthorizationError'

  /insert:
    post:
      summary: Insert MSID records
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [partyID, username, partyAPIKey]
              properties:
                partyID:
                  type: string
                username:
                  type: string
                partyAPIKey:
                  type: string
                MsidAmsidsToInsert:
                  type: array
                  description: List of MSIDs to insert
                  items:
                    type: object
                    properties:
                      row:
                        type: string
                      data:
                        type: object
                        properties:
                          BMUnitID:
                            type: string
                            maxLength: 11
                          GSPGroup:
                            type: string
                            maxLength: 2
                          effectiveFromMSIDP:
                            type: string
                            format: date
                          effectiveToMSIDP:
                            type: string
                            format: date
                          importMSID:
                            type: string
                            maxLength: 13
                          importMSIDCustomerConsentFlag:
                            type: string
                            enum: [Y, N]
                          effectiveFromICCF:
                            type: string
                            format: date
                          effectiveToICCF:
                            type: string
                            format: date
                          exportMSID:
                            type: string
                            maxLength: 13
                          exportMSIDCustomerConsentFlag:
                            type: string
                            enum: [Y, N]
                          effectiveFromECCF:
                            type: string
                            format: date
                          effectiveToECCF:
                            type: string
                            format: date
      responses:
        '200':
          description: MSIDs inserted successfully
          content:
            application/json:
              schema:
                type: object
                example:
                  status: "success"
                  jobId: "abc123"
        '400':
          $ref: '#/components/responses/InvalidParameters'
        '403':
          $ref: '#/components/responses/AuthorizationError'

  /update:
    post:
      summary: Update MSID records either {Effective From Date} Or {Customer Consent Flag} independently
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [partyID, username, partyAPIKey]
              properties:
                partyID:
                  type: string
                username:
                  type: string
                partyAPIKey:
                  type: string
              oneOf:
                - required: [MsidAmsidsToUpdate]
                  properties:
                    MsidAmsidsToUpdate:
                      type: array
                      items:
                        type: object
                        properties:
                          row:
                            type: string
                          data:
                            type: string
                            description: Format:"MSIDId,EffectiveToSettlementDate"
                - required: [ConsentFlagsToUpdate]
                  properties:
                    ConsentFlagsToUpdate:
                      type: array
                      items:
                        type: object
                        properties:
                          row:
                            type: string
                          data:
                            type: string
                            description: Format:"MSIDId,MSID,ConsentFlag,ConsentEffectiveFromDate,FlowDirection"
      responses:
        '200':
          description: MSIDs updated successfully
          content:
            application/json:
              schema:
                type: object
                example:
                  status: "success"
                  updatedRecords: 3
        '400':
          $ref: '#/components/responses/InvalidParameters'
        '403':
          $ref: '#/components/responses/AuthorizationError'

components:
  responses:
    InvalidParameters:
      description: Payload does not conform to API specification
      content:
        application/json:
          schema:
            type: object
            example:
              message: "Invalid parameters, please check the API documentation"

    AuthorizationError:
      description: Authorization failure (invalid API key or unauthorized username)
      content:
        application/json:
          schema:
            type: object
            oneOf:
              - example:
                  message: "The provided username and party combination is not authorized."
              - example:
                  message: "The provided username and partyID combination is not authorized."

    InvalidEndpoint:
      description: Operation type is invalid
      content:
        application/json:
          schema:
            type: object
            example:
              message: "Invalid endpoint. Accepted endpoints are: Read, Insert, Update"
